### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by Dafnafrank** [cosullivan/SmtpServer#38] opened 2017-06-14 12:10 UTC
Hi,
When we send an email using "Thunderbird" and sending the email with non-English encoding (for example Russian),  the mail that reaches the client is in gibberish and not as it was originally written.
I think there is a bug in the way the server handles the encoding part.
I couldn't find a way to fix this.

**Comment by cosullivan** [comment] 2017-06-14 12:54
Hi,

This should also now be fixed in v3+. There was an issue previously in how it was handling the Unicode characters. 

You can see the test here showing that it now works correctly;
https://github.com/cosullivan/SmtpServer/blob/master/Src/SmtpServer.Tests/SmtpServerTests.cs#L41

If it still doesn't work with the new version, can you please send me some more information (ie, the text that you are sending) and I will look into it.

Thanks,
Cain.

**Comment by Dafnafrank** [comment] 2017-06-14 13:07
Hi,
I think it was not resolved.
Just use Thunderbird as the mail client and send an email with the following text "שלום שלום שלום" in the body. In the "Options" -> "Text encoding" -> Choose "Hebrew Visual"
Now send the email and you will see the when you get the email it is in Gibberish and not as you wrote the body originally.
We discovered this when using Thunderbird (which is apparently a common email client...) I didn't see this happening when using Outlook.

**Comment by cosullivan** [comment] 2017-06-14 13:23
Hi,

I just added a test for these characters and it worked fine;
https://github.com/cosullivan/SmtpServer/blob/master/Src/SmtpServer.Tests/SmtpServerTests.cs#L42

Are you able to send me the complete MIME context? It will be quicker than me setting up Thunderbird, else I can have a look in the next week or so.

Thanks,
Cain.

**Comment by Dafnafrank** [comment] 2017-06-14 13:39
Maybe this is because we are not using the server correctly. 
In the previous version we used the IMimeMessage.Mime property to get the entire mime.
Since we saw you removed this class, we used instead:

```
            var message = MimeKit.Load(textMessage.Content);
            var mime = message.Body.ToString();

```
But we do not get the mime properly.
Is there a way to get the full mime like before?

**Comment by cosullivan** [comment] 2017-06-14 13:52
Ok, that will be the issue. You are only returning the body portion of the MIME content, and not the MIME headers.

MimeKit is good if you want to read the raw contents of the message into a usable object model, but if you are just interested in the plain MIME content (like it would have been previously) then the ITextMessage.Content property is that MIME content.

If you want to return it as a string, do something like this (if you want to create an extension method);

    public static string Mime(this ITextMessage textMessage)
    {
        textMessage.Content.Position = 0;

        using (var reader = new StreamReader(textMessage.Content))
        {
            return reader.ReadToEnd();
        }
    }

And that will return the MIME content, complete with headers and body.

Thanks,
Cain.

**Comment by Dafnafrank** [comment] 2017-06-14 14:05
I will try your suggestions and let you  know.
But - can you please try the same new test, just write that line in the body and not in the subject?

**Comment by Dafnafrank** [comment] 2017-06-15 06:57
We tested this scenario again and it still fails. Using Thunderbird, it's easy to change the encoding and reproduce this bug.
I have attached two files, one that holds a utf8 encoding (which works fine), and the second, contains windows-1255 encoding, which fails because we get a Gibberish email.

[utf8encoding.eml.txt](https://github.com/cosullivan/SmtpServer/files/1076821/utf8encoding.eml.txt)
[windows-1255encoding.eml.txt](https://github.com/cosullivan/SmtpServer/files/1076822/windows-1255encoding.eml.txt)

Please note, that the encoding bug is in the body and not in the subject.

**Comment by cosullivan** [comment] 2017-06-16 12:40
Are you able to share details of how you are extracting those emails to text files?

The mail server itself only deals with individual bytes and will keep reading those bytes until it receives a dot-block sequence, which effectively is the following 5 bytes "13, 10, 46, 13, 10". 

Those bytes are then available as a stream without any form of encoding/decoding, that its then up to the user.

The subject is different because that is transferred as a MIME header field and the mail client should (unless the server supports it) send these as a base64 encoded string (which it is doing in this case).

Thanks,
Cain.

**Comment by Dafnafrank** [comment] 2017-06-16 14:55
We are saving the entire mime as a file during the process, only for debugging.


Sent from my iPhone

On 16 Jun 2017, at 15:41, cosullivan <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you able to share details of how you are extracting those emails to text files?

The mail server itself only deals with individual bytes and will keep reading those bytes until it receives a dot-block sequence, which effectively is the following 5 bytes "13, 10, 46, 13, 10".

Those bytes are then available as a stream without any form of encoding/decoding, that its then up to the user.

The subject is different because that is transferred as a MIME header field and the mail client should (unless the server supports it) send these as a base64 encoded string (which it is doing in this case).

Thanks,
Cain.

**Comment by cosullivan** [comment] 2017-06-16 16:07
How are you copying it though? I am wondering if the issue is when you are writing that file to disk that the encoding is being lost as I can't see how the server wouldn't pick it up when it is just reading bytes from a network stream.

Can you try something like this;

    using (var file = File.Create("C:\\Temp\\message.bin"))
    {
        textMessage.Content.Position = 0;;
        textMessage.Content.CopyTo(file);
    }

**Comment by Dafnafrank** [comment] 2017-06-16 16:20
We encountered this bug when we got emails in Gibberish and investigated it. The emails were sent using Thunderbird.
I don't think that the encoding is being lost since we simply save it as text file.

Sent from my iPhone

On 16 Jun 2017, at 19:07, cosullivan <notifications@github.com<mailto:notifications@github.com>> wrote:


How are you copying it though? I am wondering if the issue is when you are writing that file to disk that the encoding is being lost as I can't see how the server wouldn't pick it up when it is just reading bytes from a network stream.

Can you try something like this;

using (var file = File.Create("C:\\Temp\\message.bin"))
{
    textMessage.Content.Position = 0;;
    textMessage.Content.CopyTo(file);
}

**Comment by cosullivan** [comment] 2017-06-17 09:07
I've modified on of the tests such that it allows passing of the charset property through to the message.

![image](https://user-images.githubusercontent.com/2428335/27251709-f5310816-537e-11e7-8012-9a7c6038b309.png)

If you have a look at the screenshot, the Content-Type and Content-Transfer-Encoding are the same as you example, and the characters display the same too. 

However, the test will still pass because I am using MimeKit to decode it correctly (by passing in the same charset).

I still think the issue will be on your end when you are dealing with the MIME content itself, rather that anything in the server.

**Closed** 2017-08-23 11:47 UTC
