### ISSUE TITLE
Wrong response code from MailboxFilter

### ISSUE THREAD

**Issue by azsft** [cosullivan/SmtpServer#184] opened 2022-10-20 10:35 UTC
MailboxFilterResult.NoTemporarily response from MailboxFilter returns 550 (no permanently) instead of 450 (no temporarily). Causing client will not defer message, but send NDR.

**Comment by cosullivan** [comment] 2023-10-16 03:22
Yes, you are correct here.

The issue is that there are numerous codes which the filter could return for different scenarios and I tried to simplify this. I think its probably better for the IMailboxFilter to simply return true or false and then it already will allow the implementor to throw an SmtpResponseException to control the actual code to return.

**Comment by azsft** [comment] 2023-10-16 19:02
Returning true/false from IMailboxFilter would be less confusing.

As I have been stucked to pre-defined MailboxFilterResult.NoTemporarily option with misconfigured response, so I missed that  I can just throw SmtpResponseException if I want to return specific SmtpReply code and message

**Comment by cosullivan** [comment] 2023-11-02 13:11
Hi,

This should now be fixed in v10.0.0 which is now published. 

Please note that there is a breaking change to the mailbox filter API but its a very easy modification for implementations.

**Closed by cosullivan** 2023-11-02 13:11 UTC
